### ISSUE TITLE
RuntimeError Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'

### ISSUE THREAD

**Issue by tricoffee** [VDIGPKU/CBNet_pytorch#8]
**RuntimeError**
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1 (while checking arguments for cudnn_convolution)

**environment**
one computer with 3 gpus(but i only use 2 gpus) , 
gpu : GeForce RTX 2080 Ti
cpu: i7 64g 
docker 

**modified**

add **_os.environ['CUDA_VISIBLE_DEVICES']= '2,1'_** at the begining of the script file mmdet/tools/train.py

from __future__ import division
import argparse
import copy
import os
import os.path as osp
import time

**_os.environ['CUDA_VISIBLE_DEVICES']= '2,1'_**

import mmcv
import torch
from mmcv import Config
from mmcv.runner import init_dist

from mmdet import __version__
from mmdet.apis import set_random_seed, train_detector
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.utils import collect_env, get_root_logger

**dataset**
coco2017

**bash shell**

#!/usr/bin/env bash

PYTHON=${PYTHON:-"python"}
CONFIG_FILE=configs/cbnet/faster_rcnn_db_x101_32x4d_fpn_1x.py
GPUS=2
PORT=${PORT:-29500}
CUDA_VISIBLE_DEVICES=2,1 $PYTHON -m torch.distributed.launch \
--nnodes=1 \
--nproc_per_node=${GPUS} \
--master_port=$PORT \
tools/train.py ${CONFIG_FILE} --local_rank=1 --launcher pytorch --validate

**Comment by tricoffee** [comment]
if don't load pretrained weights, this project can run but occur OOM error
2020-06-18 09:16:45,829 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2020-06-18 09:17:27,324 - mmdet - INFO - Epoch [1][50/58633]    lr: 0.00797, eta: 6 days, 18:09:39, time: 0.830, data_time: 0.126, memory: 8939, loss_rpn_cls: 0.3607, loss_rpn_bbox: 0.0821, loss_cls: 0.7505, acc: 92.8223, loss_bbox: 0.1099, loss: 1.3032
2020-06-18 09:18:03,710 - mmdet - INFO - Epoch [1][100/58633]   lr: 0.00931, eta: 6 days, 8:10:43, time: 0.728, data_time: 0.017, memory: 8939, loss_rpn_cls: 0.2673, loss_rpn_bbox: 0.0677, loss_cls: 0.4885, acc: 94.3301, loss_bbox: 0.1193, loss: 0.9428
Traceback (most recent call last):
  File "tools/train.py", line 145, in <module>
    main()
  File "tools/train.py", line 141, in main
    meta=meta)
  File "/code/CBNet/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/code/CBNet/mmdet/apis/train.py", line 185, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 384, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 290, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/code/CBNet/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 10.76 GiB total capacity; 8.51 GiB already allocated; 38.19 MiB free; 1.37 GiB cached)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/cbnet/faster_rcnn_db_x101_32x4d_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
